### ISSUE TITLE
Ensure Ports in DesiredEnvoyService() Func are as Expected

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#253]
Ensure the ports provided to the `DesiredEnvoyService()` are as expected. In Gateway test cases where Contour is updated with a bad port name, the operator panics:
```
2021-03-11T10:57:42.289-0800	INFO	gateway_controller	ensured contour service for contour	{"namespace": "contour-operator", "name": "contour-gateway-sample"}
E0311 10:57:42.289141   90885 runtime.go:78] Observed a panic: runtime.boundsError{x:1, y:1, signed:true, code:0x0} (runtime error: index out of range [1] with length 1)
goroutine 183 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x239efc0, 0xc000bae7e0)
	/Users/daneyonhansen/code/go/src/github.com/projectcontour/contour-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/daneyonhansen/code/go/src/github.com/projectcontour/contour-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x239efc0, 0xc000bae7e0)
	/usr/local/Cellar/go/1.15.4/libexec/src/runtime/panic.go:969 +0x1b9
```

This is due to a race condition where the gatewayclass is considered valid (status not updated yet), so the gateway controller ensures the Contour's child resources.

**Comment by danehans** [comment]
Closing since Gateway API support is being migrated to contour.
