### ISSUE TITLE
Support ParameterRef-less GatewayClass

### ISSUE THREAD

**Issue by danehans** [projectcontour/contour-operator#337]
**Please describe the problem you have**
`gatewayclasses.spec.parametersRef` is optional and passes validation as such. However, the operator panics for this use case:

```
2021-04-30T18:06:17.101Z	INFO	gatewayclass_controller	synced status for gatewayclass	{"name": "sample-gatewayclass"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x1369396]

goroutine 417 [running]:
github.com/projectcontour/contour-operator/internal/objects/gateway.ContourForGateway(0x1a6d918, 0xc00084f740, 0x1a7fc70, 0xc0002b3860, 0xc0000b2ea0, 0x0, 0x0, 0xc00083fb80)
	/internal/objects/gateway/gateway.go:81 +0x96
github.com/projectcontour/contour-operator/internal/operator/controller/gateway.(*reconciler).ensureGateway(0xc00013cd40, 0x1a6d918, 0xc00084f740, 0xc0000b2ea0, 0xc0000b2ea0, 0x0)
	/internal/operator/controller/gateway/controller.go:201 +0x9b
github.com/projectcontour/contour-operator/internal/operator/controller/gateway.(*reconciler).Reconcile(0xc00013cd40, 0x1a6d918, 0xc00084f740, 0xc000753e20, 0xe, 0xc000753e10, 0x7, 0xc00084f740, 0xc000030000, 0x172fc60, ...)
	/internal/operator/controller/gateway/controller.go:146 +0x3b6
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002ce5a0, 0x1a6d870, 0xc00013ce00, 0x16f51c0, 0xc000852120)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0-beta.0/pkg/internal/controller/controller.go:298 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002ce5a0, 0x1a6d870, 0xc00013ce00, 0xc000577500)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0-beta.0/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2(0xc0007523e0, 0xc0002ce5a0, 0x1a6d870, 0xc00013ce00)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0-beta.0/pkg/internal/controller/controller.go:214 +0x6b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0-beta.0/pkg/internal/controller/controller.go:210 +0x425
```

**Comment by youngnick** [comment]
This was noted on #339, but I support that, if you set up a GatewayClass with no `parametersRef`, you get all defaults.

**Comment by danehans** [comment]
@youngnick I updated this issue to focus on the panic and created https://github.com/projectcontour/contour-operator/issues/370 to highlight the need to support paramterRef-less gateway classes.
